---
Name: Payment
After: "*"
---
Schrattenholz\Delivery\DeliveryAdmin:
  extensions:
    - Schrattenholz\Payment\Payment_DeliveryAdmin_Extension
Schrattenholz\Delivery\DeliveryType:
  extensions:
    - Schrattenholz\Payment\Payment_DeliveryType_Extension
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Schrattenholz\Payment\Payment_Order_Extension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Schrattenholz\Payment\Payment_Order_Extension
Schrattenholz\OrderProfileFeature\OrderProfileFeature_ClientContainer:
  extensions:
    - Schrattenholz\Payment\PaymentMethod_SEPA_ClientContainer_Extension
Schrattenholz\OrderProfileFeature\OrderProfileFeature_Basket:
  extensions:
    - Schrattenholz\Payment\Payment_OrderProfileFeature_ClientOrder_Extension
Schrattenholz\OrderProfileFeature\OrderProfileFeature_ClientOrder:
  extensions:
    - Schrattenholz\Payment\Payment_OrderProfileFeature_ClientOrder_Extension
SilverStripe\Security\Member:
  extensions:
    - Schrattenholz\Payment\PaymentMethod_SEPA_Member_Extension
Schrattenholz\Order\OrderConfig:
  extensions:
    - Schrattenholz\Payment\Payment_OrderConfig_Extension
Schrattenholz\OrderProfileFeature\OrderCustomerGroup:
  extensions:
    - Schrattenholz\Payment\Payment_OrderProfileFeature_OrderCostumerGroup_Extension